import React, { forwardRef, useEffect } from "react";
import Head from "next/head";
import "../styles/styles.css";
import HeaderComponent from "@/components/Header/HeaderComponent";
import HomeComponent from "@/components/Home/HomeComponent";
import StacksComponent from "@/components/Stacks/StacksComponent";
import AboutExperience from "@/components/AboutExperience/AboutExperience";
import HabilitiesComponent from "@/components/Habilities/HabilitiesComponent";
import ProjectsComponent from "@/components/Projects/ProjectsComponent";
import ContactComponent from "@/components/Contact/ContactComponent";

export default function Home() {
  return (
    <>
      <Head>
        <title>João Henrique</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <HeaderComponent />
      <main>
        <HomeComponent />
        <StacksComponent />
        <AboutExperience />
        <HabilitiesComponent />
        <ProjectsComponent />
        <ContactComponent />
      </main>
    </>
  );
}
