import Head from "next/head";
import "../styles/styles.css";
import HeaderComponent from "@/components/Header/HeaderComponent";
import HomeComponent from "@/components/Home/HomeComponent";

export default function Home() {
  return (
    <>
      <Head>
        <title>João Henrique</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <HeaderComponent />
      <main>
        <HomeComponent />
      </main>
    </>
  );
}
